# DataSource Config
spring:
  application:
    name: springfox-swagger
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://localhost:3306/vueblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://rm-wz9gt1r5ii39z0yzbho.mysql.rds.aliyuncs.com:3306/vueblog?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: fanhoufang
    password: 9ex%25J7btXsQ&Z

server:
  port: 8080

shiro-redis:
  enabled: true
  redis-manager:
    host: 127.0.0.1:6379

shiroc-config:
  jwt:
    secret: f4e2e52034348f86b67cde581c0f9eb5
    expire: 604800
    header: Authorization

# ===== 自定义swagger配置 ===== #
swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 3.0
  application-description: springfox swagger 3.0
  try-host: http://localhost:${server.port}
