# 开发配置文件
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-wz9gt1r5ii39z0yzbho.mysql.rds.aliyuncs.com:3306/vueblog?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: fanhoufang
    password: 9ex%25J7btXsQ&Z

server:
  port: 8080

shiro-redis:
  enabled: true
  redis-manager:
    host: 127.0.0.1:6379

shiroc-config:
  jwt:
    secret: f4e2e52034348f86b67cde581c0f9eb5
    expire: 604800
    header: Authorization

logging:
  level:
    root: info
    com.fanhoufang: debug
    org.springframework: warn

